### ISSUE TITLE
Use `Instant` instead of `SystemTime`

### ISSUE THREAD

**Issue by PopcornPaws** [zgendao/auth-service#11]
`Instant` is monotonic, meaning that assigning `instant_1 = Instant::now()` and `instant_2 = Instant::now()` to consecutive events in real time will ensure that `instant_1 < instant_2`. This is not the case with `SystemTime`. See [`Instant` docs](https://doc.rust-lang.org/std/time/struct.Instant.html) and [`SystemTime` docs](https://doc.rust-lang.org/std/time/struct.SystemTime.html) for more info.

**Comment by gyozosz** [comment]
`Instant` is an opaque type that can not represent a point in time, it is only usable in combination with another `Instant` instance to produce a `Duration` (or for comparison). Consequently, time information cannot be stored in a database using them.

**Comment by PopcornPaws** [comment]
Alright, I think we can close this issue then and keep using `SystemTime`.
